image: "theimpulson/gitlab-ci-android:android-34"

before_script: 
- export GRADLE_USER_HOME=$(pwd)/.gradle
- chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
  - .gradle/

stages:
- build

assembleNightly:
  stage: build
  script:
  - ./gradlew assembleNightly
  artifacts:
    paths:
    - app/build/outputs/apk/nightly/app-nightly.apk
